exe: Main.cpp
	clang++ *.cpp `sdl-config --cflags --libs` -lSDL_image -lSDL_mixer -lSDL_ttf -Iincludes#./Source/*.cpp 

debug:
	g++ -g *.cpp `sdl-config --cflags --libs` -lSDL_image -lSDL_mixer -lSDL_ttf -Iincludes#./Source/*.cpp 

run:
	./a.out

r:
	./a.out

clean:
	#rm a.out *.cpp~ ./Source/*.h~ ./Source/*.cpp~ Makefile~

c:
	#rm a.out *.cpp~ ./Source/*.h~ ./Source/*.cpp~

